package com.example.user.geographyquiz;

/**
 * Created by user on 08/01/2017.
 */
public class CapitalCityCollection extends Quiz {

    public CapitalCityCollection() {

        collection.put("Afghanistan", "Kabul");
        collection.put("Albania", "Tirana");
        collection.put("Algeria", "Algiers");
        collection.put("Andorra", "Andorra la Vella");
        collection.put("Angola", "Luanda");
        collection.put("Antigua and Barbuda", "Saint John's");
        collection.put("Argentina", "Buenos Aires");
        collection.put("Armenia", "Yerevan");
        collection.put("Australia", "Canberra");
        collection.put("Austria", "Vienna");
        collection.put("Azerbaijan", "Baku");
        collection.put("Bahamas", "Nassau");
        collection.put("Bahrain", "Manama");
        collection.put("Bangladesh", "Dhaka");
        collection.put("Barbados", "Bridgetown");
        collection.put("Belarus", "Minsk");
        collection.put("Belgium", "Brussels");
        collection.put("Belize", "Belmopan");
        collection.put("Benin", "Porto-Novo");
        collection.put("Bhutan", "Thimphu");
        collection.put("Bolivia", "La Paz");
        collection.put("Bosnia and Herzegovina", "Sarajevo");
        collection.put("Botswana", "Gaborone");
        collection.put("Brazil", "Brasilia");
        collection.put("Brunei", "Bandar Seri Begawan");
        collection.put("Bulgaria", "Sofia");
        collection.put("Burkina Faso", "Ouagadougou");
        collection.put("Burundi", "Bujumbura");
        collection.put("Cabo Verde", "Praia");
        collection.put("Cambodia", "Phnom Penh");
        collection.put("Cameroon", "Yaounde");
        collection.put("Canada", "Ottawa");
        collection.put("Central African Republic", "Bangui");
        collection.put("Chad", "N'Djamena");
        collection.put("Chile", "Santiago");
        collection.put("China", "Beijing");
        collection.put("Colombia", "Bogotá");
        collection.put("Comoros", "Moroni");
        collection.put("the Democratic Republic of the Congo", "Kinshasa");
        collection.put("the Republic of the Congo", "Brazzaville");
        collection.put("Costa Rica", "San Jose");
        collection.put("Cote d'Ivoire", "Yamoussoukro");
        collection.put("Croatia", "Zagreb");
        collection.put("Cuba", "Havana");
        collection.put("Cyprus", "Nicosia");
        collection.put("Czech Republic", "Prague");
        collection.put("Denmark", "Copenhagen");
        collection.put("Djibouti", "Djibouti");
        collection.put("Dominica", "Roseau");
        collection.put("the Dominican Republic", "Santo Domingo");
        collection.put("Ecuador", "Quito");
        collection.put("Egypt", "Cairo");
        collection.put("El Salvador", "San Salvador");
        collection.put("Equatorial Guinea", "Malabo");
        collection.put("Eritrea", "Asmara");
        collection.put("Estonia", "Tallinn");
        collection.put("Ethiopia", "Addis Ababa");
        collection.put("Fiji", "Suva");
        collection.put("Finland", "Helsinki");
        collection.put("France", "Paris");
        collection.put("Gabon", "Libreville");
        collection.put("Gambia", "Banjul");
        collection.put("Georgia", "Tbilisi");
        collection.put("Germany", "Berlin");
        collection.put("Ghana", "Accra");
        collection.put("Greece", "Athens");
        collection.put("Grenada", "Saint George's");
        collection.put("Guatemala", "Guatemala City");
        collection.put("Guinea", "Conakry");
        collection.put("Guinea-Bissau", "Bissau");
        collection.put("Guyana", "Georgetown");
        collection.put("Haiti", "Port-au-Prince");
        collection.put("Honduras", "Tegucigalpa");
        collection.put("Hungary", "Budapest");
        collection.put("Iceland", "Reykjavik");
        collection.put("India", "New Delhi");
        collection.put("Indonesia", "Jakarta");
        collection.put("Iran", "Tehran");
        collection.put("Iraq", "Baghdad");
        collection.put("Ireland", "Dublin");
        collection.put("Israel", "Jerusalem");
        collection.put("Italy", "Rome");
        collection.put("Jamaica", "Kingston");
        collection.put("Japan", "Tokyo");
        collection.put("Jordan", "Amman");
        collection.put("Kazakhstan", "Astana");
        collection.put("Kenya", "Nairobi");
        collection.put("Kiribati", "South Tarawa");
        collection.put("Kosovo", "Pristina");
        collection.put("Kuwait", "Kuwait City");
        collection.put("Kyrgyzstan", "Bishkek");
        collection.put("Laos", "Vientiane");
        collection.put("Latvia", "Riga");
        collection.put("Lebanon", "Beirut");
        collection.put("Lesotho", "Maseru");
        collection.put("Liberia", "Monrovia");
        collection.put("Libya", "Tripoli");
        collection.put("Liechtenstein", "Vaduz");
        collection.put("Lithuania", "Vilnius");
        collection.put("Luxembourg", "Luxembourg");
        collection.put("Macedonia", "Skopje");
        collection.put("Madagascar", "Antananarivo");
        collection.put("Malawi", "Lilongwe");
        collection.put("Malaysia", "Kuala Lumpur");
        collection.put("the Maldives", "Male");
        collection.put("Mali", "Bamako");
        collection.put("Malta", "Valletta");
        collection.put("the Marshall Islands", "Majuro");
        collection.put("Mauritania", "Nouakchott");
        collection.put("Mauritius", "Port Louis");
        collection.put("Mexico", "Mexico City");
        collection.put("Micronesia", "Palikir");
        collection.put("Moldova", "Chisinau");
        collection.put("Monaco", "Monaco");
        collection.put("Mongolia", "Ulaanbaatar");
        collection.put("Montenegro", "Podgorica");
        collection.put("Morocco", "Rabat");
        collection.put("Mozambique", "Maputo");
        collection.put("Myanmar", "Naypyidaw");
        collection.put("Namibia", "Windhoek");
        collection.put("Nauru", "Yaren District");
        collection.put("Nepal", "Kathmandu");
        collection.put("Netherlands", "Amsterdam");
        collection.put("New Zealand", "Wellington");
        collection.put("Nicaragua", "Managua");
        collection.put("Niger", "Niamey");
        collection.put("Nigeria", "Abuja");
        collection.put("North Korea", "Pyongyang");
        collection.put("Norway", "Oslo");
        collection.put("Oman", "Muscat");
        collection.put("Pakistan", "Islamabad");
        collection.put("Palau", "Ngerulmud");
        collection.put("Palestine", "Ramallah");
        collection.put("Panama", "Panama City");
        collection.put("Papua New Guinea", "Port Moresby");
        collection.put("Paraguay", "Asunción");
        collection.put("Peru", "Lima");
        collection.put("Philippines", "Manila");
        collection.put("Poland", "Warsaw");
        collection.put("Portugal", "Lisbon");
        collection.put("Qatar", "Doha");
        collection.put("Romania", "Bucharest");
        collection.put("Russia", "Moscow");
        collection.put("Rwanda", "Kigali");
        collection.put("Saint Kitts and Nevis", "Basseterre");
        collection.put("Saint Lucia", "Castries");
        collection.put("Saint Vincent and the Grenadines", "Kingstown");
        collection.put("Samoa", "Apia");
        collection.put("San Marino", "San Marino");
        collection.put("Sao Tome and Principe", "São Tomé");
        collection.put("Saudi Arabia", "Riyadh");
        collection.put("Senegal", "Dakar");
        collection.put("Serbia", "Belgrade");
        collection.put("the Seychelles", "Victoria");
        collection.put("Sierra Leone", "Freetown");
        collection.put("Singapore", "Singapore");
        collection.put("Slovakia", "Bratislava");
        collection.put("Slovenia", "Ljubljana");
        collection.put("the Solomon Islands", "Honiara");
        collection.put("Somalia", "Mogadishu");
        collection.put("South Africa", "Pretoria");
        collection.put("South Korea", "Seoul");
        collection.put("South Sudan", "Juba");
        collection.put("Spain", "Madrid");
        collection.put("Sri Lanka", "Sri Jayawardenepura Kotte");
        collection.put("Sudan", "Khartoum");
        collection.put("Suriname", "Paramaribo");
        collection.put("Swaziland", "Mbabane");
        collection.put("Sweden", "Stockholm");
        collection.put("Switzerland", "Bern");
        collection.put("Syria", "Damascus");
        collection.put("Taiwan", "Taipei");
        collection.put("Tajikistan", "Dushanbe");
        collection.put("Tanzania", "Dodoma");
        collection.put("Thailand", "Bangkok");
        collection.put("Timor-Leste", "Dili");
        collection.put("Togo", "Lomé");
        collection.put("Tonga", "Nukuʻalofa");
        collection.put("Trinidad and Tobago", "Port of Spain");
        collection.put("Tunisia", "Tunis");
        collection.put("Turkey", "Ankara");
        collection.put("Turkmenistan", "Ashgabat");
        collection.put("Tuvalu", "Funafuti");
        collection.put("Uganda", "Kampala");
        collection.put("Ukraine", "Kyiv");
        collection.put("the United Arab Emirates", "Abu Dhabi");
        collection.put("the United Kingdom", "London");
        collection.put("the United States of America", "Washington D.C.");
        collection.put("Uruguay", "Montevideo");
        collection.put("Uzbekistan", "Tashkent");
        collection.put("Vanuatu", "Port Vila");
        collection.put("the Vatican City", "Vatican City");
        collection.put("Venezuela", "Caracas");
        collection.put("Vietnam", "Hanoi");
        collection.put("Yemen", "Sana'a");
        collection.put("Zambia", "Lusaka");
        collection.put("Zimbabwe", "Harare");
    }
}
